name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../../packages/bloc
  flutter_bloc:
    path: ../../packages/flutter_bloc
  hydrated_bloc:
    path: ../../packages/hydrated_bloc
  path_provider: ^2.0.1

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  flutter_bloc:
    path: ../../packages/flutter_bloc
  hydrated_bloc:
    path: ../../packages/hydrated_bloc
  bloc_test:
    path: ../../packages/bloc_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
    path: ../../packages/bloc_test
  mocktail: ^0.2.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
